feat: add zeno blog
deepin-community/planet-deepin-org pull request #5
Opened 2023-02-03 06:35 UTC by Zeno-sole

2023-02-03 06:36 UTC, Zeno-sole commented
@BLumia

2023-02-03 08:28 UTC, BLumia commented on planet.ini
> +tags     = deepin
感觉这个模板当时提供的有点歧义，tags 是表示在爬取后加到这个源的文章上的额外标签，不是指爬取后过滤只显示这个源里指定标签的文章。

这里你的目的是前者吗？

2023-02-06 04:49 UTC, BLumia commented on planet.ini
> +tags     = deepin
如果不是的话，这一行可以直接删掉

2023-02-06 04:50 UTC, BLumia requested changes

2023-02-06 04:50 UTC, BLumia commented on planet.ini
> +[myml]
```suggestion
[zeno]
```

2023-02-06 04:50 UTC, BLumia commented on planet.ini
> +keep_categories = deepin
cnblogs 不会把标签导出为 category，所以 cnblogs 用不了这个特性 = =

2023-02-06 05:14 UTC, BLumia approved these changes

2023-02-06 08:33 UTC, merged